"""
Curated DSA & FAANG question sets with LeetCode links and solution links.
"""

DSA_TOPICS = {
    "Arrays & Hashing": [
        {"title": "Two Sum", "difficulty": "Easy", "company": ["Google","Amazon","Facebook"],
         "lc": "https://leetcode.com/problems/two-sum/",
         "solution": "https://www.youtube.com/watch?v=KLlXCFG5TnA",
         "note": "Classic hash map problem"},
        {"title": "Best Time to Buy and Sell Stock", "difficulty": "Easy", "company": ["Amazon","Facebook"],
         "lc": "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
         "solution": "https://www.youtube.com/watch?v=1pkOgXD63yU",
         "note": "Sliding window / Kadane variant"},
        {"title": "Contains Duplicate", "difficulty": "Easy", "company": ["Apple"],
         "lc": "https://leetcode.com/problems/contains-duplicate/",
         "solution": "https://www.youtube.com/watch?v=3OamzN90kPg",
         "note": "HashSet O(n)"},
        {"title": "Product of Array Except Self", "difficulty": "Medium", "company": ["Facebook","Amazon","Microsoft"],
         "lc": "https://leetcode.com/problems/product-of-array-except-self/",
         "solution": "https://www.youtube.com/watch?v=bNvIQI2wAjk",
         "note": "Prefix/suffix products"},
        {"title": "Maximum Subarray", "difficulty": "Medium", "company": ["Google","Amazon"],
         "lc": "https://leetcode.com/problems/maximum-subarray/",
         "solution": "https://www.youtube.com/watch?v=5WZl3MMT0Eg",
         "note": "Kadane's algorithm"},
        {"title": "Top K Frequent Elements", "difficulty": "Medium", "company": ["Facebook","Amazon"],
         "lc": "https://leetcode.com/problems/top-k-frequent-elements/",
         "solution": "https://www.youtube.com/watch?v=YPTqKIgVk-k",
         "note": "Bucket sort / heap"},
        {"title": "Longest Consecutive Sequence", "difficulty": "Medium", "company": ["Google","Facebook"],
         "lc": "https://leetcode.com/problems/longest-consecutive-sequence/",
         "solution": "https://www.youtube.com/watch?v=P6RZZMu_maU",
         "note": "HashSet O(n)"},
    ],
    "Two Pointers": [
        {"title": "Valid Palindrome", "difficulty": "Easy", "company": ["Facebook"],
         "lc": "https://leetcode.com/problems/valid-palindrome/",
         "solution": "https://www.youtube.com/watch?v=jJXJ16kPFWg",
         "note": "Two pointer from both ends"},
        {"title": "3Sum", "difficulty": "Medium", "company": ["Google","Facebook","Amazon"],
         "lc": "https://leetcode.com/problems/3sum/",
         "solution": "https://www.youtube.com/watch?v=jzZsG8n2R9A",
         "note": "Sort then two pointer"},
        {"title": "Container With Most Water", "difficulty": "Medium", "company": ["Google","Facebook"],
         "lc": "https://leetcode.com/problems/container-with-most-water/",
         "solution": "https://www.youtube.com/watch?v=UuiTKBwPgAo",
         "note": "Greedy two pointer"},
        {"title": "Trapping Rain Water", "difficulty": "Hard", "company": ["Google","Facebook","Amazon"],
         "lc": "https://leetcode.com/problems/trapping-rain-water/",
         "solution": "https://www.youtube.com/watch?v=ZI2z5pq0TqA",
         "note": "Two pointer or stack"},
    ],
    "Sliding Window": [
        {"title": "Longest Substring Without Repeating Characters", "difficulty": "Medium", "company": ["Amazon","Facebook","Google"],
         "lc": "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
         "solution": "https://www.youtube.com/watch?v=wiGpQwVHdE0",
         "note": "HashSet sliding window"},
        {"title": "Minimum Window Substring", "difficulty": "Hard", "company": ["Facebook","Google"],
         "lc": "https://leetcode.com/problems/minimum-window-substring/",
         "solution": "https://www.youtube.com/watch?v=jSto0O4AJbM",
         "note": "Two pointer + frequency map"},
        {"title": "Sliding Window Maximum", "difficulty": "Hard", "company": ["Google","Amazon"],
         "lc": "https://leetcode.com/problems/sliding-window-maximum/",
         "solution": "https://www.youtube.com/watch?v=DfljaUwZsOk",
         "note": "Deque based O(n)"},
    ],
    "Stack": [
        {"title": "Valid Parentheses", "difficulty": "Easy", "company": ["Google","Facebook","Amazon"],
         "lc": "https://leetcode.com/problems/valid-parentheses/",
         "solution": "https://www.youtube.com/watch?v=WTzjTskDFMg",
         "note": "Classic stack problem"},
        {"title": "Min Stack", "difficulty": "Medium", "company": ["Amazon","Google"],
         "lc": "https://leetcode.com/problems/min-stack/",
         "solution": "https://www.youtube.com/watch?v=qkLl7nAwDPo",
         "note": "Two stacks"},
        {"title": "Daily Temperatures", "difficulty": "Medium", "company": ["Google","Amazon"],
         "lc": "https://leetcode.com/problems/daily-temperatures/",
         "solution": "https://www.youtube.com/watch?v=cTBiBSnjO3c",
         "note": "Monotonic stack"},
        {"title": "Largest Rectangle in Histogram", "difficulty": "Hard", "company": ["Google","Facebook"],
         "lc": "https://leetcode.com/problems/largest-rectangle-in-histogram/",
         "solution": "https://www.youtube.com/watch?v=zx5Sw9130L0",
         "note": "Monotonic stack"},
    ],
    "Binary Search": [
        {"title": "Binary Search", "difficulty": "Easy", "company": ["Google","Facebook","Amazon"],
         "lc": "https://leetcode.com/problems/binary-search/",
         "solution": "https://www.youtube.com/watch?v=s4DPM8ct1pI",
         "note": "Template for BS"},
        {"title": "Search in Rotated Sorted Array", "difficulty": "Medium", "company": ["Facebook","Amazon","Microsoft"],
         "lc": "https://leetcode.com/problems/search-in-rotated-sorted-array/",
         "solution": "https://www.youtube.com/watch?v=U8XENwh8Oy8",
         "note": "Modified binary search"},
        {"title": "Find Minimum in Rotated Sorted Array", "difficulty": "Medium", "company": ["Google","Microsoft"],
         "lc": "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/",
         "solution": "https://www.youtube.com/watch?v=nIVW4P8b1VA",
         "note": "Binary search variant"},
        {"title": "Median of Two Sorted Arrays", "difficulty": "Hard", "company": ["Google","Amazon","Apple"],
         "lc": "https://leetcode.com/problems/median-of-two-sorted-arrays/",
         "solution": "https://www.youtube.com/watch?v=q6IEA26hvXc",
         "note": "Binary search on smaller array"},
    ],
    "Trees": [
        {"title": "Invert Binary Tree", "difficulty": "Easy", "company": ["Google","Facebook"],
         "lc": "https://leetcode.com/problems/invert-binary-tree/",
         "solution": "https://www.youtube.com/watch?v=OnSn2XEQ4MY",
         "note": "Recursive DFS"},
        {"title": "Maximum Depth of Binary Tree", "difficulty": "Easy", "company": ["Facebook","Google"],
         "lc": "https://leetcode.com/problems/maximum-depth-of-binary-tree/",
         "solution": "https://www.youtube.com/watch?v=hTM3phVI6YQ",
         "note": "BFS or DFS"},
        {"title": "Lowest Common Ancestor of BST", "difficulty": "Medium", "company": ["Facebook","Amazon"],
         "lc": "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/",
         "solution": "https://www.youtube.com/watch?v=gs2LMfuOR9k",
         "note": "BST property"},
        {"title": "Binary Tree Level Order Traversal", "difficulty": "Medium", "company": ["Amazon","Microsoft","Facebook"],
         "lc": "https://leetcode.com/problems/binary-tree-level-order-traversal/",
         "solution": "https://www.youtube.com/watch?v=6ZnyEApgFYg",
         "note": "BFS with queue"},
        {"title": "Serialize and Deserialize Binary Tree", "difficulty": "Hard", "company": ["Facebook","Google"],
         "lc": "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/",
         "solution": "https://www.youtube.com/watch?v=u4JAi2JJhI8",
         "note": "DFS preorder"},
    ],
    "Dynamic Programming": [
        {"title": "Climbing Stairs", "difficulty": "Easy", "company": ["Google","Amazon","Apple"],
         "lc": "https://leetcode.com/problems/climbing-stairs/",
         "solution": "https://www.youtube.com/watch?v=Y0lT9Fck7qI",
         "note": "Fibonacci DP"},
        {"title": "Coin Change", "difficulty": "Medium", "company": ["Google","Amazon","Facebook"],
         "lc": "https://leetcode.com/problems/coin-change/",
         "solution": "https://www.youtube.com/watch?v=H9bfqozjoqs",
         "note": "Bottom-up DP"},
        {"title": "Longest Increasing Subsequence", "difficulty": "Medium", "company": ["Google","Microsoft","Amazon"],
         "lc": "https://leetcode.com/problems/longest-increasing-subsequence/",
         "solution": "https://www.youtube.com/watch?v=cjWnW0hdF1Y",
         "note": "DP + patience sort"},
        {"title": "0/1 Knapsack", "difficulty": "Medium", "company": ["Google","Amazon"],
         "lc": "https://leetcode.com/problems/partition-equal-subset-sum/",
         "solution": "https://www.youtube.com/watch?v=IsvocB5BJhw",
         "note": "Classic knapsack"},
        {"title": "Edit Distance", "difficulty": "Hard", "company": ["Google","Facebook"],
         "lc": "https://leetcode.com/problems/edit-distance/",
         "solution": "https://www.youtube.com/watch?v=XYi2-LPrwm4",
         "note": "2D DP"},
    ],
    "Graphs": [
        {"title": "Number of Islands", "difficulty": "Medium", "company": ["Google","Facebook","Amazon"],
         "lc": "https://leetcode.com/problems/number-of-islands/",
         "solution": "https://www.youtube.com/watch?v=pV2kpPD66nE",
         "note": "DFS/BFS flood fill"},
        {"title": "Clone Graph", "difficulty": "Medium", "company": ["Facebook","Google"],
         "lc": "https://leetcode.com/problems/clone-graph/",
         "solution": "https://www.youtube.com/watch?v=mQeF6bN8hMk",
         "note": "DFS with hashmap"},
        {"title": "Course Schedule", "difficulty": "Medium", "company": ["Google","Facebook","Amazon"],
         "lc": "https://leetcode.com/problems/course-schedule/",
         "solution": "https://www.youtube.com/watch?v=EgI5nU9etnU",
         "note": "Topological sort / cycle detection"},
        {"title": "Word Ladder", "difficulty": "Hard", "company": ["Google","Facebook","Amazon"],
         "lc": "https://leetcode.com/problems/word-ladder/",
         "solution": "https://www.youtube.com/watch?v=h9iTnkgv05E",
         "note": "BFS shortest path"},
    ],
    "Linked List": [
        {"title": "Reverse Linked List", "difficulty": "Easy", "company": ["Facebook","Google","Amazon"],
         "lc": "https://leetcode.com/problems/reverse-linked-list/",
         "solution": "https://www.youtube.com/watch?v=G0_I-ZF0S38",
         "note": "Iterative or recursive"},
        {"title": "Merge Two Sorted Lists", "difficulty": "Easy", "company": ["Amazon","Microsoft","Apple"],
         "lc": "https://leetcode.com/problems/merge-two-sorted-lists/",
         "solution": "https://www.youtube.com/watch?v=XIdigk956u0",
         "note": "Two pointers on lists"},
        {"title": "Linked List Cycle", "difficulty": "Easy", "company": ["Amazon","Microsoft"],
         "lc": "https://leetcode.com/problems/linked-list-cycle/",
         "solution": "https://www.youtube.com/watch?v=gBTe7lFR3vc",
         "note": "Floyd's algorithm"},
        {"title": "Merge k Sorted Lists", "difficulty": "Hard", "company": ["Google","Amazon","Facebook"],
         "lc": "https://leetcode.com/problems/merge-k-sorted-lists/",
         "solution": "https://www.youtube.com/watch?v=q5a5OiGbT6Q",
         "note": "Min heap / divide and conquer"},
    ],
}

FAANG_COMPANY_DATA = {
    "Google": {
        "color": "#4285F4",
        "icon": "🔵",
        "focus": ["System Design","Algorithms","Data Structures","Coding"],
        "rounds": 5,
        "tips": [
            "Explain your thought process clearly",
            "Start with brute force, then optimize",
            "Ask clarifying questions",
            "Practice Google-style system design (scale to 1B users)",
            "Strong focus on Big O analysis",
        ],
        "hot_topics": ["Graphs","Trees","Dynamic Programming","System Design"],
        "glassdoor": "https://www.glassdoor.com/Interview/Google-Software-Engineer-Interview-Questions-EI_IE9079.0,6_KO7,24.htm",
        "prep_guide": "https://igotanoffer.com/blogs/tech/google-software-engineer-interview",
    },
    "Amazon": {
        "color": "#FF9900",
        "icon": "🟡",
        "focus": ["Leadership Principles","Coding","System Design","Behavioral"],
        "rounds": 6,
        "tips": [
            "STAR format for behavioral questions",
            "Know all 16 Leadership Principles deeply",
            "Practice design at scale (AWS-level)",
            "Strong on arrays, trees, graphs",
            "Ownership and customer obsession examples",
        ],
        "hot_topics": ["Arrays","Trees","DP","OOP Design"],
        "glassdoor": "https://www.glassdoor.com/Interview/Amazon-Software-Engineer-Interview-Questions-EI_IE6036.0,6_KO7,24.htm",
        "prep_guide": "https://igotanoffer.com/blogs/tech/amazon-software-engineer-interview",
    },
    "Apple": {
        "color": "#555555",
        "icon": "⚪",
        "focus": ["Coding","System Design","Cultural Fit","Domain Knowledge"],
        "rounds": 4,
        "tips": [
            "Show passion for Apple products",
            "Clean, readable code matters",
            "Focus on optimization and efficiency",
            "Strong OOP and design patterns",
            "Attention to detail in UI/UX discussions",
        ],
        "hot_topics": ["Graphs","Strings","OOP","Concurrency"],
        "glassdoor": "https://www.glassdoor.com/Interview/Apple-Software-Engineer-Interview-Questions-EI_IE1138.0,5_KO6,23.htm",
        "prep_guide": "https://igotanoffer.com/blogs/tech/apple-software-engineer-interview",
    },
    "Netflix": {
        "color": "#E50914",
        "icon": "🔴",
        "focus": ["Senior Leadership","System Design","High Scale","Cultural Fit"],
        "rounds": 4,
        "tips": [
            "Netflix hires senior only – show leadership",
            "Freedom and responsibility culture",
            "Design for 220M+ users",
            "Strong opinion on technical choices",
            "Chaos engineering mindset",
        ],
        "hot_topics": ["Distributed Systems","Caching","CDN","Microservices"],
        "glassdoor": "https://www.glassdoor.com/Interview/Netflix-Software-Engineer-Interview-Questions-EI_IE11891.0,7_KO8,25.htm",
        "prep_guide": "https://igotanoffer.com/blogs/tech/netflix-software-engineer-interview",
    },
    "Meta (Facebook)": {
        "color": "#1877F2",
        "icon": "🔷",
        "focus": ["Coding","System Design","Behavioral","Product Sense"],
        "rounds": 5,
        "tips": [
            "Move fast, ship quickly mindset",
            "Graph problems heavily tested",
            "Product design for billions",
            "Strong on recursion and trees",
            "Behavioral: past impact stories",
        ],
        "hot_topics": ["Graphs","Trees","Recursion","Distributed Systems"],
        "glassdoor": "https://www.glassdoor.com/Interview/Meta-Software-Engineer-Interview-Questions-EI_IE40772.0,4_KO5,23.htm",
        "prep_guide": "https://igotanoffer.com/blogs/tech/facebook-software-engineer-interview",
    },
    "Microsoft": {
        "color": "#00A4EF",
        "icon": "🔹",
        "focus": ["Coding","OOP","System Design","Behavioral"],
        "rounds": 4,
        "tips": [
            "Strong emphasis on OOP & Design Patterns",
            "Test your code for edge cases",
            "Growth mindset is key",
            "Collaborative problem solving",
            "Azure cloud knowledge is a plus",
        ],
        "hot_topics": ["Arrays","Strings","Trees","OOP Design"],
        "glassdoor": "https://www.glassdoor.com/Interview/Microsoft-Software-Engineer-Interview-Questions-EI_IE1651.0,9_KO10,27.htm",
        "prep_guide": "https://igotanoffer.com/blogs/tech/microsoft-software-engineer-interview",
    },
}

APTITUDE_QUESTIONS = [
    # Quantitative
    {"category": "Quantitative", "question": "A train 125m long passes a pole in 5 seconds. What is the speed in km/hr?",
     "options": ["80","90","100","72"], "answer": "90",
     "explanation": "Speed = 125/5 = 25 m/s = 25×18/5 = 90 km/hr"},
    {"category": "Quantitative", "question": "If 8 men can do a job in 12 days, in how many days can 12 men do the same job?",
     "options": ["6","7","8","9"], "answer": "8",
     "explanation": "Man-days = 8×12 = 96. 12 men take 96/12 = 8 days"},
    {"category": "Quantitative", "question": "What is 15% of 400?",
     "options": ["55","60","65","70"], "answer": "60",
     "explanation": "15/100 × 400 = 60"},
    {"category": "Quantitative", "question": "A sum doubles in 5 years at simple interest. What is the rate?",
     "options": ["15%","20%","25%","10%"], "answer": "20%",
     "explanation": "SI = P, so P×R×5/100 = P → R = 20%"},
    {"category": "Quantitative", "question": "Pipe A fills a tank in 4 hours, Pipe B drains it in 12 hours. How long to fill if both open?",
     "options": ["4h","6h","8h","10h"], "answer": "6h",
     "explanation": "Net rate = 1/4 - 1/12 = 1/6. Time = 6 hours"},

    # Logical Reasoning
    {"category": "Logical", "question": "All birds can fly. Penguins are birds. Can penguins fly?",
     "options": ["Yes","No","Cannot determine","Depends"], "answer": "Yes",
     "explanation": "By strict logical deduction from given premises (not real world). Answer: Yes per syllogism."},
    {"category": "Logical", "question": "Complete the series: 2, 6, 12, 20, 30, ?",
     "options": ["40","42","44","46"], "answer": "42",
     "explanation": "n(n+1): 1×2=2, 2×3=6, 3×4=12, ... 6×7=42"},
    {"category": "Logical", "question": "If ROAD is coded as URDG, how is SWAN coded?",
     "options": ["VZDQ","VZEQ","YZDQ","VZDP"], "answer": "VZDQ",
     "explanation": "Each letter +3: S→V, W→Z, A→D, N→Q"},
    {"category": "Logical", "question": "Find the odd one out: 2, 3, 5, 7, 11, 15",
     "options": ["11","15","7","3"], "answer": "15",
     "explanation": "All are prime except 15 (= 3×5)"},

    # Verbal
    {"category": "Verbal", "question": "Choose the word most similar to EPHEMERAL:",
     "options": ["Permanent","Transient","Eternal","Constant"], "answer": "Transient",
     "explanation": "Ephemeral means lasting for a very short time = Transient"},
    {"category": "Verbal", "question": "Identify the grammatically correct sentence:",
     "options": [
         "Neither of the boys have done their homework.",
         "Neither of the boys has done his homework.",
         "Neither of the boys has done their homework.",
         "Neither of the boys have done his homework."
     ], "answer": "Neither of the boys has done his homework.",
     "explanation": "'Neither' takes singular verb 'has' and singular pronoun 'his'"},

    # Technical Aptitude
    {"category": "Technical", "question": "What is the time complexity of binary search?",
     "options": ["O(n)","O(log n)","O(n log n)","O(1)"], "answer": "O(log n)",
     "explanation": "Each step halves the search space → O(log n)"},
    {"category": "Technical", "question": "Which data structure uses LIFO?",
     "options": ["Queue","Stack","Array","Heap"], "answer": "Stack",
     "explanation": "Stack: Last In First Out (LIFO)"},
    {"category": "Technical", "question": "How many bits in an IPv4 address?",
     "options": ["16","32","64","128"], "answer": "32",
     "explanation": "IPv4 = 4 octets × 8 bits = 32 bits"},
    {"category": "Technical", "question": "What does SQL stand for?",
     "options": [
         "Structured Query Language",
         "Simple Query Language",
         "Sequential Query Language",
         "Standard Query Language"
     ], "answer": "Structured Query Language",
     "explanation": "SQL = Structured Query Language"},
]

POPULAR_FACTS = [
    {"fact": "The first computer bug was an actual bug — a moth found inside a Harvard Mark II computer in 1947.", "category": "Tech History"},
    {"fact": "Google's first tweet was 'I'm feeling lucky' in binary code.", "category": "Google"},
    {"fact": "The term 'algorithm' comes from the name of Persian mathematician Al-Khwarizmi.", "category": "Computer Science"},
    {"fact": "The world's first website (info.cern.ch) is still live today — it was created in 1991.", "category": "Tech History"},
    {"fact": "Python was named after the British comedy group 'Monty Python', not the snake.", "category": "Programming"},
    {"fact": "The first 1GB hard drive (1980) weighed 550 lbs and cost $40,000.", "category": "Tech History"},
    {"fact": "Amazon was originally called 'Cadabra' (as in Abracadabra).", "category": "Amazon"},
    {"fact": "Facebook's original name was 'TheFacebook', launched only for Harvard students.", "category": "Meta"},
    {"fact": "More people in the world own a smartphone than own a toothbrush.", "category": "General"},
    {"fact": "The '@' symbol is called 'ampersat', 'arroba' in Spanish, and 'monkey tail' in Dutch.", "category": "General"},
]

MOTIVATIONAL_QUOTES = [
    {"quote": "The only way to do great work is to love what you do.", "author": "Steve Jobs"},
    {"quote": "Programs must be written for people to read, and only incidentally for machines to execute.", "author": "Harold Abelson"},
    {"quote": "First, solve the problem. Then, write the code.", "author": "John Johnson"},
    {"quote": "Talk is cheap. Show me the code.", "author": "Linus Torvalds"},
    {"quote": "The best error message is the one that never shows up.", "author": "Thomas Fuchs"},
    {"quote": "Code is like humor. When you have to explain it, it's bad.", "author": "Cory House"},
    {"quote": "It's not a bug – it's an undocumented feature.", "author": "Anonymous"},
    {"quote": "Simplicity is the soul of efficiency.", "author": "Austin Freeman"},
    {"quote": "Before software can be reusable it first has to be usable.", "author": "Ralph Johnson"},
    {"quote": "Make it work, make it right, make it fast.", "author": "Kent Beck"},
    {"quote": "Every great developer you know got there by solving problems they were unqualified to solve.", "author": "Patrick McKenzie"},
    {"quote": "The most disastrous thing that you can ever learn is your first programming language.", "author": "Alan Kay"},
    {"quote": "Measuring programming progress by lines of code is like measuring aircraft building progress by weight.", "author": "Bill Gates"},
    {"quote": "Any fool can write code that a computer can understand. Good programmers write code that humans can understand.", "author": "Martin Fowler"},
    {"quote": "In order to be irreplaceable, one must always be different.", "author": "Coco Chanel"},
]

AI_WORKFLOWS = [
    {
        "tool": "ChatGPT / Claude",
        "icon": "🤖",
        "category": "Writing & Reasoning",
        "use_cases": [
            "Draft, edit, and improve code explanations",
            "Generate LeetCode solution approaches",
            "Summarize research papers instantly",
            "Create study schedules and plans",
            "Practice mock interview Q&A",
        ],
        "power_features": "System prompts, multi-turn conversations, code interpreter",
        "workflow": "Describe problem → Ask for approach → Request optimized code → Ask for edge cases",
        "link": "https://chat.openai.com",
    },
    {
        "tool": "GitHub Copilot",
        "icon": "👾",
        "category": "Code Generation",
        "use_cases": [
            "Auto-complete entire functions",
            "Generate boilerplate code instantly",
            "Suggest test cases automatically",
            "Translate between programming languages",
            "Debug with AI suggestions inline",
        ],
        "power_features": "Copilot Chat, inline suggestions, whole-file context",
        "workflow": "Write function signature → Copilot completes → Review → Accept/Modify",
        "link": "https://github.com/features/copilot",
    },
    {
        "tool": "Notion AI",
        "icon": "📝",
        "category": "Productivity & Notes",
        "use_cases": [
            "Auto-summarize long study notes",
            "Generate study plans from rough ideas",
            "Create flashcards from notes",
            "Organize research automatically",
            "Build project management templates",
        ],
        "power_features": "AI blocks, slash commands, database summaries",
        "workflow": "Dump raw notes → AI summarize → Create action items → Track progress",
        "link": "https://notion.so",
    },
    {
        "tool": "Perplexity AI",
        "icon": "🔍",
        "category": "Research & Search",
        "use_cases": [
            "Research interview topics with citations",
            "Find latest tech news and trends",
            "Compare programming languages/frameworks",
            "Understand complex CS concepts",
            "Fact-check information instantly",
        ],
        "power_features": "Real-time search, citations, follow-up questions",
        "workflow": "Ask technical question → Get sourced answer → Deep dive with follow-ups",
        "link": "https://perplexity.ai",
    },
    {
        "tool": "Zapier / Make (Integromat)",
        "icon": "⚡",
        "category": "Automation",
        "use_cases": [
            "Auto-save LeetCode problems to Notion",
            "Daily digest emails of CS news",
            "GitHub activity → Slack notifications",
            "Auto-schedule study sessions on Google Calendar",
            "Track coding hours automatically",
        ],
        "power_features": "Multi-step zaps, webhooks, AI steps",
        "workflow": "Trigger event → Filter/Transform → Action → Notification",
        "link": "https://zapier.com",
    },
    {
        "tool": "Otter.ai / Fireflies",
        "icon": "🎙️",
        "category": "Meeting & Audio",
        "use_cases": [
            "Transcribe mock interview recordings",
            "Auto-summarize recorded lectures",
            "Search through study session recordings",
            "Track action items from study groups",
            "Generate notes from voice memos",
        ],
        "power_features": "Real-time transcription, speaker identification, AI summary",
        "workflow": "Record session → Auto transcribe → AI summarize → Export notes",
        "link": "https://otter.ai",
    },
    {
        "tool": "Midjourney / DALL-E",
        "icon": "🎨",
        "category": "Visual Creation",
        "use_cases": [
            "Create visual representations of algorithms",
            "Generate data structure diagrams",
            "Visualize system architecture concepts",
            "Create presentation assets quickly",
            "Design custom icons for projects",
        ],
        "power_features": "Style prompting, image variations, inpainting",
        "workflow": "Describe concept → Generate → Refine prompt → Export",
        "link": "https://midjourney.com",
    },
    {
        "tool": "v0 by Vercel",
        "icon": "🏗️",
        "category": "UI Generation",
        "use_cases": [
            "Generate UI components from text",
            "Prototype portfolio websites instantly",
            "Create dashboard mockups",
            "Design system components on demand",
            "Convert Figma ideas to code",
        ],
        "power_features": "React/Tailwind output, iteration, copy-paste ready",
        "workflow": "Describe UI → Generate → Iterate → Copy code → Deploy",
        "link": "https://v0.dev",
    },
]

CODING_LANGUAGES = {
    "Python": {
        "icon": "🐍",
        "level": "Beginner Friendly",
        "resources": [
            {"name": "Python Official Docs", "url": "https://docs.python.org/3/"},
            {"name": "Real Python", "url": "https://realpython.com/"},
            {"name": "Python for Everybody (Coursera)", "url": "https://www.coursera.org/specializations/python"},
            {"name": "Automate the Boring Stuff", "url": "https://automatetheboringstuff.com/"},
        ]
    },
    "C++": {
        "icon": "⚡",
        "level": "Intermediate",
        "resources": [
            {"name": "cppreference.com", "url": "https://cppreference.com"},
            {"name": "learncpp.com", "url": "https://learncpp.com"},
            {"name": "C++ Primer (Book)", "url": "https://www.amazon.com/Primer-5th-Stanley-B-Lippman/dp/0321714113"},
            {"name": "Competitive Programmer's Handbook", "url": "https://cses.fi/book/book.pdf"},
        ]
    },
    "Java": {
        "icon": "☕",
        "level": "Intermediate",
        "resources": [
            {"name": "Oracle Java Docs", "url": "https://docs.oracle.com/en/java/"},
            {"name": "Baeldung", "url": "https://www.baeldung.com/"},
            {"name": "Java Brains (YouTube)", "url": "https://www.youtube.com/@JavaBrains"},
            {"name": "Effective Java (Book)", "url": "https://www.amazon.com/Effective-Java-Joshua-Bloch/dp/0134685997"},
        ]
    },
    "JavaScript": {
        "icon": "🟡",
        "level": "Beginner Friendly",
        "resources": [
            {"name": "MDN Web Docs", "url": "https://developer.mozilla.org/en-US/docs/Web/JavaScript"},
            {"name": "javascript.info", "url": "https://javascript.info/"},
            {"name": "FreeCodeCamp JS", "url": "https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/"},
            {"name": "You Don't Know JS", "url": "https://github.com/getify/You-Dont-Know-JS"},
        ]
    },
    "Go": {
        "icon": "🐹",
        "level": "Intermediate",
        "resources": [
            {"name": "Tour of Go", "url": "https://go.dev/tour/"},
            {"name": "Go by Example", "url": "https://gobyexample.com/"},
            {"name": "Effective Go", "url": "https://go.dev/doc/effective_go"},
        ]
    },
    "Rust": {
        "icon": "🦀",
        "level": "Advanced",
        "resources": [
            {"name": "The Rust Book", "url": "https://doc.rust-lang.org/book/"},
            {"name": "Rustlings", "url": "https://github.com/rust-lang/rustlings"},
            {"name": "Rust by Example", "url": "https://doc.rust-lang.org/rust-by-example/"},
        ]
    },
}

BADGES = {
    "first_login": {"icon": "🎯", "name": "First Login", "desc": "Welcome to FAANG Prep!"},
    "streak_7": {"icon": "🔥", "name": "Week Warrior", "desc": "7-day login streak"},
    "streak_30": {"icon": "💎", "name": "Month Master", "desc": "30-day login streak"},
    "note_taker": {"icon": "📝", "name": "Note Taker", "desc": "Created your first note"},
    "link_sharer": {"icon": "🔗", "name": "Link Collector", "desc": "Added 5+ custom links"},
    "fitness_fan": {"icon": "💪", "name": "Fitness Fan", "desc": "Logged 7 workouts"},
    "quiz_master": {"icon": "🧠", "name": "Quiz Master", "desc": "Aced the aptitude test"},
    "code_ninja": {"icon": "🥷", "name": "Code Ninja", "desc": "Visited all DSA sections"},
    "api_connected": {"icon": "🔌", "name": "API Wizard", "desc": "Connected all coding profiles"},
    "explorer": {"icon": "🗺️", "name": "Explorer", "desc": "Visited all pages"},
}
